export const DATA =[
  {
    FAMILIA: "ACCIDENTES Y EMERGENCIAS",
    REQUERIMIENTO: [
      "ACCIDENTE DE TRANSITO",
      "EMERGENCIA DE SALUD",
      "MASCULINO EXTRAVIADO",
      "POSTE, SEMAFORO O SEÑALETICA CAIDA",
      "POSTE, SEMAFORO O SEÑALETICA CON RIESGO DE CAIDA",
      "ADULTO MAYOR EXTRAVIADO",
      "ARBOL O RAMA CAIDA",
      "FEMENINA EXTRAVIADO",
      "INCENDIO EN LUGAR HABITADO",
      "MASCULINO ATRAPADO",
      "FEMENINA ATRAPADO",
      "VEHICULO INCENDIANDOSE",
      "INCENDIO EN LUGAR NO HABITADO",
      "INCENDIO EN PASTIZAL Y/O BASURA",
      "INUNDACION, ANEGAMIENTO, FUGA DE AGUA"
    ]
  },
  {
    FAMILIA: "ACCIONES EN PATRULLAJE MUNICIPAL",
    REQUERIMIENTO: [
      "ENCARGO O HALLAZGO DE VEHICULO ROBADO",
      "ACTIVIDAD O SUJETO SOSPECHOSA",
      "SEMAFORO APAGADO",
      "VEHICULO ABANDONADO",
      "DETENCION Y/O RETENCION CIUDADANA",
      "VEHICULO MAL ESTACIONADO",
      "FISCALIZACIONES DE TRANSITO",
      "RONDA PREVENTIVA",
      "RETIRO DE RUCO",
      "LUMINARIAS APAGADAS",
      "CONFLICTO VECINAL",
      "CABLES CAIDOS U A BAJA ALTURA",
      "SOLICITUDES SERVICIOS MUNICIPALES",
      "ALARMA ACTIVADA",
      "FISCALIZACIONES A LOCAL COMERCIAL"
    ]
  },
  {
    FAMILIA: "DELITOS ASOCIADOS A ARMAS",
    REQUERIMIENTO: [
      "AMENAZAS CON ARMAS",
      "DISPARO INJUSTIFICADO",
      "LESIONADO CON ARMA DE FUEGO"
    ]
  },
  {
    FAMILIA: "DELITOS CONTRA LA PROPIEDAD NO VIOLENTOS",
    REQUERIMIENTO: [
      "ROBO DE VEHICULO",
      "ROBO DE ARTICULOS DENTRO DE UN VEHICULO",
      "ROBO AL COMERCIO",
      "ROBO EN LUGAR HABITADO",
      "ROBO DE CABLES EN EL ESPACIO PUBLICO",
      "ROBO EN LUGAR NO HABITADO",
      "ROBO MEDIANTE VEHICULO"
    ]
  },
  {
    FAMILIA: "DELITOS VIOLENTOS",
    REQUERIMIENTO: [
      "INTENTO DE ROBO",
      "ROBO CON INTIMIDACION Y VIOLENCIA",
      "MUERTE Y/O HALLAZGO DE CADAVER",
      "VIOLENCIA INTRAFAMILIAR A MUJER",
      "ROBO DE VEHICULO CON VIOLENCIA",
      "RIÑA EN VIA PUBLICA",
      "RIÑA EN RECINTO PRIVADO",
      "LESIONES LEVES",
      "LESIONADO/S",
      "PRESUNTA DESGRACIA",
      "LESIONES Y/O AGRESIONES A PERSONAS",
      "VIOLENCIA INTRAFAMILIAR NO CLASIFICADA",
      "VIOLENCIA INTRAFAMILIAR EN CONTEXTO DE PAREJA",
      "VIOLENCIA INTRAFAMILIAR A NIÑO O NIÑA"
    ]
  },
  {
    FAMILIA: "INCIVILIDADES",
    REQUERIMIENTO: [
      "RUIDOS MOLESTOS",
      "CONSUMO DE ALCOHOL O DROGAS EN VIA PUBLICA",
      "ANIMALES SUELTOS EN LA VIA PUBLICA",
      "ESCOMBROS EN LA VIA PUBLICA",
      "OTRAS INCIVILIDADES",
      "PROBLEMAS PERSONAS EN SITUACION DE CALLE",
      "AGRESION A FUNCIONARIO PUBLICO",
      "AGRESION A MENOR DE EDAD",
      "DETONACION DE FUEGOS ARTIFICIALES",
      "AGRESION A FEMENINA",
      "DESORDENES EN LA VIA PUBLICA",
      "COMERCIO NO AUTORIZADO EN LA VIA PUBLICA",
      "AMENAZAS",
      "OFENSAS AL PUDOR",
      "DAÑOS A BIENES DE USO PUBLICO",
      "AGRESION A ADULTO MAYOR",
      "COMERCIO ILEGAL",
      "JUEGOS INFLABLES O PISCINAS OBSTRUYENDO LA VIA PUBLICA",
      "PERSONA TIRADA EN LA VIA PUBLICA",
      "MICROBASURALES"
    ]
  },
  {
    FAMILIA: "OTROS DELITOS O FALTAS",
    REQUERIMIENTO: [
      "OTROS",
      "OTROS DELITOS O FALTAS",
      "VULNERACION A ADULTO MAYOR",
      "ESTAFA Y/O DELITOS FINANCIEROS",
      "USURPACION DE TERRENO",
      "USURPACION DE PROPIEDAD PRIVADA (CASA TOMADA)"
    ]
  }
]